/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static int BinarySearch (int [] arr, int key){
        int index=0, count=0;

        for (int element: arr) {
            if (element == key){
                index= count;

            }else {
                index=-1;
            }
            count++;
        }

        return index;
    }
    public static void main(String[] args) {

        int[]arr= {4, 8, 15, 16, 23, 42};
        int[]arr1= {-131, -82, 0, 27, 42, 68, 179};
        int[]arr2= {11, 22, 33, 44, 55, 66, 77};
        int[]arr3= {1, 2, 3, 5, 6, 7};
        int ind= BinarySearch(arr3, 4);
        System.out.println("The index is: "+ ind);
    }
}
