import java.util.ArrayList;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static ArrayList<Integer> sumationOfMatrix(int[][] arr){
        ArrayList<Integer>sum=new ArrayList<Integer>();
        int summation=0;

        for (int i = 0; i < arr.length; i++) {
            for (int j = 0; j < arr[i].length; j++) {
                summation+=arr[i][j];
            }
            sum.add(summation);
            summation=0;
        }
        return sum;
    }
    public static void main(String[] args) {

        int[][] arr= {{1, 2, 3},{3, 5, 7},{1, 7, 10}};
        int[][] arr2= {{0, 1, 5},{-4, 7, 2},{-3, 12, 11}};
        System.out.println(sumationOfMatrix(arr2).toString());
    }
}
